<a href="https://colab.research.google.com/github/Signeemmanuel/research-journey-2025/blob/master/Notebooks/Phase_1_Foundation/Day_003_Matrix_Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
import os
import subprocess
import sys

# 1. Mount Drive
drive.mount('/content/drive')

# --- CONFIGURATION ---
REPO_DIR = "/content/drive/MyDrive/Research-Journey-2025"
TOOLS_DIR = f"{REPO_DIR}/Colab_Tools"

# 2. Initialize Environment
if os.path.exists(TOOLS_DIR):
    print("🚀 Initializing Environment...")
    !python "{TOOLS_DIR}/setup_ssh.py"
    !python "{TOOLS_DIR}/manage_repo.py"
    print("\n✅ READY TO CODE.")
else:
    print("❌ Error: Colab_Tools not found. Check your Drive paths.")

Mounted at /content/drive
🚀 Initializing Environment...
🔑 INITIALIZING SSH ENVIRONMENT...
🌐 Scanning GitHub keys...
# github.com:22 SSH-2.0-40744a1
👤 Configuring Git Global Identity...
Testing connection...
Hi Signeemmanuel! You've successfully authenticated, but GitHub does not provide shell access.
✅ SSH Setup Complete.
📦 MANAGING REPOSITORY: /content/drive/MyDrive/Research-Journey-2025
🔄 Repository exists. Pulling latest changes...
Updating 7ffffc1..d105e57
error: Your local changes to the following files would be overwritten by merge:
	Day_001_Foundation.ipynb
Please commit your changes or stash them before you merge.
Aborting
Traceback (most recent call last):
  File "/content/drive/MyDrive/Research-Journey-2025/Colab_Tools/manage_repo.py", line 29, in <module>
    main()
  File "/content/drive/MyDrive/Research-Journey-2025/Colab_Tools/manage_repo.py", line 24, in main
    subprocess.run("git pull", shell=True, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in r

# Torch and setup

In [3]:
import torch
import numpy as np

print(f"Pytorch version: {torch.__version__}")

# Set a random seed for reproducability
torch.manual_seed(42)

Pytorch version: 2.9.0+cu126


# Defining Matrices

In [4]:
# Create tensor with shape (2, 3)
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
], dtype=torch.float32)

# Create tensor with shape (3, 2)
B = torch.tensor([
    [7, 8],
    [9, 1],
    [2, 3]
], dtype=torch.float32)

print(f"Matrix A shape: {A.shape}")
print(f"Matrix B shape: {B.shape}")
print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A shape: torch.Size([2, 3])
Matrix B shape: torch.Size([3, 2])

Matrix A:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

Matrix B:
 tensor([[7., 8.],
        [9., 1.],
        [2., 3.]])


# Matrix Multiplication (A x B)

In [5]:
# Method 1: torch.matmul()
C = torch.matmul(A, B)

# Method 2: the @ operator (Standard python for Matrix Mult)
C_prime = A @ B

print(f"Result shape: {C.shape}") # should be (2, 2)
print("\nResult Matrix C:\n", C)

# Verify both methods are identical
assert torch.allclose(C, C_prime)
print("\nAssertion Passed: torch.matmul matches @ operator")

Result shape: torch.Size([2, 2])

Result Matrix C:
 tensor([[31., 19.],
        [85., 55.]])

Assertion Passed: torch.matmul matches @ operator


# Non Commutativity (B x A)

In [6]:
D = B @ A

print(f"Result D (B @ A) Shape: {D.shape}")
print("\n Result Matrix D\n", D)

Result D (B @ A) Shape: torch.Size([3, 3])

 Result Matrix D
 tensor([[39., 54., 69.],
        [13., 23., 33.],
        [14., 19., 24.]])


# Element-wise vs Matrix Multiplication



In [7]:
#Let's create two square matrices to test this
X = torch.tensor([[1, 2], [3, 4]])
Y = torch.tensor([[5, 6], [7, 8]])

# 1. Element-wise multiplication (hadamard Product)
element_wise = X * Y
print("X * Y (Element-wise):\n", element_wise)

# 2. Matrix Multication
matrix_mult = X @ Y
print("\nX @ Y (Matrix Mult):\n", matrix_mult)

X * Y (Element-wise):
 tensor([[ 5, 12],
        [21, 32]])

X @ Y (Matrix Mult):
 tensor([[19, 22],
        [43, 50]])


In [8]:
# The Transpose operation

In [15]:
A_T = A.T

print(f"Original A shape: {A.shape}")
print(f"Transposed A shape: {A_T.shape}")

print("\n Original A:\n", A)

print("\n Transposed A:\n", A_T)

squared_A = A @ A_T
print(f"\nSquared A shape: {squared_A.shape}")

print("\nSquared A: \n", squared_A)

Original A shape: torch.Size([2, 3])
Transposed A shape: torch.Size([3, 2])

 Original A:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

 Transposed A:
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

Squared A shape: torch.Size([2, 2])

Squared A: 
 tensor([[14., 32.],
        [32., 77.]])
